version: '3'
services:
  app:
    image: php
    build: docker/php
    ports:
    - 80:80
    volumes:
    - .:/app
    command: php -S 0.0.0.0:80 app/public/index.php
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
